--- # this is my conditionals playbook
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
          - name: installing apche2 in debian
            command: yum install apache2 -y
            when: ansible_os_family == "Debian"


          - name: installing httpd in redhat
            command: yum install httpd -y
            when: ansible_os_family == "RedHat"

